# Generated by Django 4.1 on 2022-09-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('tipo_producto', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_id', models.IntegerField()),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('direccion_proveedor', models.CharField(max_length=50)),
                ('cuit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_id', models.IntegerField()),
                ('fecha_venta', models.DateField()),
                ('cantidad_venta', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
            ],
        ),
    ]
